Model Parameters:
  batch_size: 128
  epochs: 500
  num_workers: 0
  name_dataset: 'mp_gap'
  path_dataset: '/mnt/netapp1/Store_CSIC//home/csic/qud/ebm/datasets/matbench'
  len_dataset: 30000
  name: 'GATom'
  internal_params:
    hidden_channels: 150
    pre_conv_layers: 2
    post_conv_layers: 2
    layers_attention: 4
    num_timesteps: 2
    recurrent_cell: 'ligru'
    pooling: 'global_add_pool'
    aggregation: 'add'
    activation: 'relu'
    heads:  2
    residual_connection: True
    task: 'regression'
    dropout: 0.0
  early_stopping: True
  bool_plot: True

Optimizer Parameters:
  name: AdamW
  params:
    lr: 1.0e-4
    weight_decay: 1.0e-2

Scheduler Parameters:
  name: "ReduceLROnPlateau"
  params:
    mode: "min"
    factor: 0.8
    patience: 10
    threshold: 1.0e-3
    min_lr: 1.0e-7
