Model Parameters:
  batch_size: 128
  epochs: 500
  graph_algorithm: "KNN"
  name: 'GATom'
  internal_params:
    hidden_channels: 150
    pre_conv_layers: 2
    post_conv_layers: 2
    layers_attention: 4
    pooling: 'global_add_pool'
    aggregation: 'add'
    activation: 'relu'
    activation_cell: 'silu'
    heads:  2
    residual_connection: True
    task: 'regression'
    dropout: 0.0
  early_stopping: True
  bool_plot: True

Optimizer Parameters:
  name: AdamW
  params:
    lr: 1.0e-4
    weight_decay: 1.0e-2

Scheduler Parameters:
  name: SequentialLR
  milestones: [10]
  sub_schedulers:
      name: LinearLR
      params: 
        start_factor: 0.1
        total_iters: 10
      name: CosineAnnealingLR
      params: 
        T_max: 500 
        eta_min: 1.0e-6

