Model Parameters:
  batch_size: 128
  epochs: 500
  graph_algorithm: "KNN"
  name: 'IMcgcnn'
  internal_params:
    hidden_channels: 150
    num_layers: 3
    pre_conv_layers: 2
    post_conv_layers: 2
    activation: "relu"
    pooling: "global_mean_pool"
    task: "regression"
    residual_connection: False
    dropout: 0.0
  early_stopping: True
  bool_plot: True

Optimizer Parameters:
  name: AdamW
  lr: 1.0e-4
  weight_decay: 1.0e-2

Scheduler Parameters:
  name: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.8
  patience: 10
  threshold: 1.0e-3
  min_lr: 1.0e-7
