Model Parameters:
  batch_size: 128
  bool_plot: true
  early_stopping: false
  graph_algorithm: KNN
  internal_params:
    activation: relu
    aggregation: add
    dropout: 0.6667097102251842
    glu_over_gru: true
    heads: 3
    hidden_channels: 175
    layers_attention: 3
    num_timesteps: 1
    pooling: global_mean_pool
    post_conv_layers: 3
    pre_conv_layers: 1
    recurrent_cell: null
    residual_connection: false
    task: classification
  name: GATom
  num_workers: 4
Optimizer Parameters:
  name: AdamW
  params:
    lr: 0.0005710843995353203
    weight_decay: 0.0036308331516633884
Scheduler Parameters:
  name: ReduceLROnPlateau
  params:
    factor: 0.8
    min_lr: 1.0e-07
    mode: min
    patience: 10
