Model Parameters:
  batch_size: 32
  bool_plot: true
  early_stopping: false
  graph_algorithm: KNN
  internal_params:
    activation: silu
    aggregation: add
    dropout: 0.5719580639422589
    glu_over_gru: true
    heads: 4
    hidden_channels: 175
    layers_attention: 3
    num_timesteps: 1
    pooling: global_mean_pool
    post_conv_layers: 3
    pre_conv_layers: 1
    recurrent_cell: null
    residual_connection: false
    task: regression
  name: GATom
  num_workers: 4
Optimizer Parameters:
  name: AdamW
  params:
    lr: 0.0001215753474694341
    weight_decay: 0.0026762531503301953
Scheduler Parameters:
  name: ReduceLROnPlateau
  params:
    factor: 0.8
    min_lr: 1.0e-07
    mode: min
    patience: 10
