Model Parameters:
  batch_size: 64
  bool_plot: true
  early_stopping: false
  graph_algorithm: KNN
  internal_params:
    activation: relu
    aggregation: max
    dropout: 0.04860104602372278
    glu_over_gru: true
    heads: 3
    hidden_channels: 200
    layers_attention: 10
    num_timesteps: 1
    pooling: global_mean_pool
    post_conv_layers: 3
    pre_conv_layers: 1
    recurrent_cell: null
    residual_connection: true
    task: regression
  name: GATom
  num_workers: 4
Optimizer Parameters:
  name: AdamW
  params:
    lr: 7.610428445587642e-05
    weight_decay: 0.0008641159325504183
Scheduler Parameters:
  name: ReduceLROnPlateau
  params:
    factor: 0.8
    min_lr: 1.0e-07
    mode: min
    patience: 10
