Model Parameters:
  batch_size: 32
  bool_plot: true
  early_stopping: false
  graph_algorithm: Voronoi
  cell_type: UnitCell
  internal_params:
    hidden_channels: 256
    layers_attention: 3
    pre_conv_layers: 3
    post_conv_layers: 4
    dropout: 0.1
    heads: 4
    aggregation: add
    pooling: global_mean_pool
    activation: leaky_relu
    activation_cell: relu
    line_graph: true
    task: regression
    layers_attention_line: 1
  name: GATom
Optimizer Parameters:
  name: AdamW
  params:
    lr: 5.0e-05
    weight_decay: 0.05
Scheduler Parameters:
  milestones:
  - 10
  name: SequentialLR
  sub_schedulers:
  - name: LinearLR
    params:
      start_factor: 0.1
      total_iters: 10
  - name: CosineAnnealingLR
    params:
      T_max: 990
      eta_min: 1.0e-07
