Model Parameters:
  batch_size: 16
  bool_plot: true
  early_stopping: false
  graph_algorithm: KNN
  cell_type: UnitCell
  internal_params:
    hidden_channels: 128
    layers_attention: 2
    pre_conv_layers: 2
    post_conv_layers: 4
    dropout: 0.6000000000000001
    heads: 4
    aggregation: add
    pooling: global_mean_pool
    activation: leaky_relu
    activation_cell: gelu
    line_graph: false
    task: regression
    layers_attention_line: null
  name: GATom
Optimizer Parameters:
  name: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.05
Scheduler Parameters:
  milestones:
  - 10
  name: SequentialLR
  sub_schedulers:
  - name: LinearLR
    params:
      start_factor: 0.1
      total_iters: 10
  - name: CosineAnnealingLR
    params:
      T_max: 990
      eta_min: 1.0e-07
