Model Parameters:
  batch_size: 128
  bool_plot: true
  early_stopping: false
  graph_algorithm: KNN
  internal_params:
    activation: silu
    aggregation: softmax
    dropout: 0.0011041234498524455
    glu_over_gru: true
    heads: 3
    hidden_channels: 200
    layers_attention: 10
    num_timesteps: 1
    pooling: global_add_pool
    post_conv_layers: 3
    pre_conv_layers: 1
    recurrent_cell: null
    residual_connection: true
    task: regression
  name: GATom
  num_workers: 4
Optimizer Parameters:
  name: AdamW
  params:
    lr: 0.0002910717194738612
    weight_decay: 0.0005017475121713695
Scheduler Parameters:
  name: ReduceLROnPlateau
  params:
    factor: 0.8
    min_lr: 1.0e-07
    mode: min
    patience: 10
